# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "brainfix"

# TODO: define a target for each of your executables/libraries like this:
#[target.myexecutable]
#type = "executable" # static, shared
#sources = ["src/brainfix/*.cpp", "include/brainfix/*.hpp"]
#include-directories = ["include"]
#compile-features = ["cxx_std_11"]
#link-libraries = ["target-or-library"]

[fetch-content.argparse]
git = "https://github.com/p-ranav/argparse"
tag = "v3.1"


[target.bfx]
type = "executable"
compile-features = ["cxx_std_20"]
sources = ["bfx-compiler/src/**.cpp", "bfx-compiler/autogen/**.cpp"]
headers = ["bfx-compiler/include/**.hpp"]
include-directories = ["bfx-compiler/include", "bx-compiler/autogen"]
link-libraries = ["argparse::argparse"]

[target.bfint]
type = "executable"
compile-features = ["cxx_std_20"]
sources = ["bfx-interpreter/src/**.cpp"]
headers = ["bfx-interpreter/include/**.hpp"]
include-directories = ["bfx-interpreter/include"]